version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_USER: test   #创建test用户
      MYSQL_PASSWORD: test  #设置test用户的密码
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./conf/conf.d:/etc/mysql/conf.d"